---
- name: main server config
  hosts: dev.safecast.org
  sudo: yes
  gather_facts: no
  roles:
    - base
  vars:
    deploy_path: /home/safecast/safecastapi
    deploy_version: master
  vars_files:
    - keys.yml

